apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-test
  template:
    metadata:
      labels:
        app: aci-test
    spec:
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
        volumeMounts:
          - name: volume-fulltest-uuid-used-for1-testing23456
            mountPath: /input
        resources:
          limits:
            memory: 1G
            cpu: 1
          requests:
            memory: 1G
            cpu: 1
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
      volumes:
        - name: volume-fulltest-uuid-used-for1-testing23456
          azureFile:
            shareName: "dzkubv1"
            readOnly: false
            secretName: azurefilev1-secret