apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{KEYVAULT_NAME}}
    objects:  |
      array:
        - |
          objectName: mysecret
          objectType: secret
          objectVersion: ""
    tenantId: {{AZURE_TENANTID}}